<a href="https://colab.research.google.com/github/anibjoshi/ML-math-prep/blob/main/MLM_Linear_Algebra_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 4 - Introduction to NumPy Arrays

In [ ]:
from numpy import array

l = [1.0,2.0,3.0]
a = array(l)

print(a)
print(a.shape)
print(a.dtype)

In [ ]:
from numpy import empty
a = empty([3,3])
print(a)

In [ ]:
from numpy import zeros
a = zeros([3,5])
print(a)

In [ ]:
from numpy import ones
a = ones([5])
print(a)

In [ ]:
from numpy import array
from numpy import vstack

a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)

a3 = vstack((a1,a2))
print(a3)
print(a3.shape)

In [ ]:
from numpy import array
from numpy import hstack

a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)

a3 = hstack((a1,a2))
print(a3)
print(a3.shape)

Chapter 5 - Index, Slice and Reshape NumPy Arrays

In [ ]:
# create one-dimensional array

from numpy import array

data = [11,22,33,44,55]
data = array(data)

print(data)
print(type(data))

In [ ]:
from numpy import array

data = [[11,22], 
        [33,44],
        [55,66]]

data = array(data)
print(data)
print(type(data))

In [ ]:
#index a one dimensional array
from numpy import array

data = array([11,22,33,44,55])
print(data[0])
print(data[4])

print(data[-1])
print(data[-5])

In [ ]:
#index a two dimensional array

from numpy import array

data = [[11,22], 
        [33,44],
        [55,66]]

data = array(data)
print(data[2,])

In [ ]:
#slice a one dimesional array
from numpy import array

data = array([11,22,33,44,55])
print(data[-4:])

In [ ]:
#split input and output data

from numpy import array
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])

X, y = data[:,:-1], data[:,-1]
print(X)
print(y)

In [ ]:
#split input and output data

from numpy import array
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])

split = 2
train, test = data[:split,:],data[split:,:]
print(train)
print(test)

In [ ]:
#shape of one-dimensional array
from numpy import array

data = array([11,22,33,44,55])
print(data.shape)

In [ ]:
from numpy import array

data = [[11,22], 
        [33,44],
        [55,66]]

data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

In [ ]:
#reshape 1D array to 2D

from numpy import array

data = array([11,22,33,44,55])
print(data.shape)

data = data.reshape((data.shape[0],1))
print(data)

In [ ]:
#reshape 2D array to 3D

from numpy import array

data = [[11,22], 
        [33,44],
        [55,66]]

data = array(data)
print(data.shape)

data = data.reshape((data.shape[0],data.shape[1],1))
print(data)
print(data.shape)

Chapter 6: NumPy Array Broadcasting

In [ ]:
#Arrays with different sizes cannot be used in arithmetic. A way to overcome this is to duplicate the smaller array so that it has the dimensionality and size of the larger array. This is called array broadcasting

a = [1,2,3]
b = [1,2,3]

c = a + b
c =[1+1,2+2,3+3]
print(c)

In [ ]:
# scalar and one dimensional array

from numpy import array
a = array([1,2,3])
print(a)
b = 2
print(b)
c = a + b
print(c)

In [ ]:
#broadcast scalar to a two dimensional array

A = array([
    [1,2,3],
    [1,2,3]])
print(A)
b = 2
print(b)

C = A + b
print(C)

In [ ]:
A = array([
    [1,2,3],
    [1,2,3]])
b = array([[1,5,3],[2,4,6]])
C = A + b
print(C)

Chapter 7: Set Axis for Rows and Columns

In [ ]:
#enumerate columns in numpy array

from numpy import asarray
#define data as a list
data = [[1,2,3],[4,5,6]]
#convert to a numpy array
data = asarray(data)
for col in range(data.shape[1]):
  print(data[:,col])

In [ ]:
#axis = None: Apply operation to the entire array
#axis = 0: Apply operation column-wise, across all rows for each column
#axis = 1: Apply operation row-wise, across all columns for each row

from numpy import asarray
data = [[1,2,3],[4,5,6]]
data = asarray(data)
result = data.sum(axis = None)
print(result)

In [ ]:
from numpy import asarray
data = [[1,2,3],[4,5,6]]
data = asarray(data)
result = data.sum(axis = 0)
print(result)

In [ ]:
from numpy import asarray
data = [[1,2,3],[4,5,6]]
data = asarray(data)
result = data.sum(axis = 1)
print(result)

Chapter 8: Vectors and Vector Arithmetic

In [82]:
#Vector is a tuple of one or more values.

In [84]:
#create a vector

from numpy import array

v = array([1,2,3])
print(v)

[1 2 3]


In [85]:
#vector addition
a = array([1,2,3])
b = array([1,2,3])

c = a + b
print(c)

[2 4 6]


In [87]:
#vector subtraction
a = array([1,2,3])
b = array([0.5,1.5,2.5])

c = a - b
print(c)

[0.5 0.5 0.5]


In [88]:
#vector multiplication
a = array([1,2,3])
b = array([1,2,3])

c = a * b
print(c)

[1 4 9]


In [89]:
#vector division
a = array([1,2,3])
b = array([1,2,3])

c = a / b
print(c)

[1. 1. 1.]


In [90]:
#vector multiplication
a = array([1,2,3])
b = array([1,2,3])

c = a.dot(b)
d = a @ b
print(c)
print(d)

14
14


In [91]:
#vector scalar multiplication
a = array([1,2,3])
b = 2

c = a * b
print(c)

[2 4 6]
